version: "3"
services:
  nextjs:
    container_name: nextjs-web
    image: nextjs
    build: ./
    command: npm start
    ports:
      - "3001:3000"
    networks:
      - app_network

networks:
  app_network:
    name: myapp_network
    driver: bridge